# Utiliza una imagen base de PostgreSQL
FROM postgres:latest

# Establece las variables de entorno para el usuario y contraseña de la base de datos
ENV POSTGRES_USER=polls
ENV POSTGRES_PASSWORD=polls

EXPOSE 5432

#docker build -t my-postgres-image .
#docker run -d --name my-postgres-container my-postgres-image
#al parecer el contenedor se instala sin casi nada apt-get update && apt-get install -y postgresql-client

